version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: booking
    ports:
      - "3307:3306"
    volumes:
      - ~/mysql-container-data:/var/lib/mysql
